In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
import numpy as np
y = [1,2,3,4,5]
print(y)
print(type(y))


[1, 2, 3, 4, 5]
<class 'list'>


In [4]:
import numpy as np          
print(np.__version__)

1.26.4


In [5]:
import numpy as np         
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
import numpy as np         
x = [1,2,3,4,5]
y = np.array([1,2,3,4,5])
print(y)
print(type(y))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
l = []
for i in range(1,5):
    int_1 = input("enter : ")
    l.append(int_1)
    
print(np.array(l))



['1,2,3,4,4' '1' '3' '12345']


In [8]:

import numpy as np          
arr = np.array([1,2,3,4,5,6,6,7])
print(arr)

[1 2 3 4 5 6 6 7]


In [9]:
import numpy as np           
arr = np.array(42)
print(arr)

42


In [10]:
import numpy as np         

y = np.array([1,2,3,4,5])
print(y)
print(type(y))
print(y.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [12]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print(arr2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [16]:
import numpy as np          
x = ([[1,2,3,4,5,6],[9,8,7,6,5,4]])
print(x)
print(type(x))

[[1, 2, 3, 4, 5, 6], [9, 8, 7, 6, 5, 4]]
<class 'list'>


In [25]:
import numpy as np            
arr = ([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

print(type(arr))

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]
<class 'list'>


In [1]:
import numpy as np          

a = np.array(43)
b = np.array([1,2,3,4])
c = np.array([[1,2,3,4],[5,6,7,8]])
d = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [3]:
import numpy as np          
arr = np.array([1,2,3,4], ndmin=6)
print(arr)
print(arr.ndim)


[[[[[[1 2 3 4]]]]]]
6


In [4]:
import numpy as np           
arr = np.array([1,2,3,4,5,6,7], ndmin=10)
print(arr)
print(arr.ndim)

[[[[[[[[[[1 2 3 4 5 6 7]]]]]]]]]]
10


In [7]:
import numpy as np          
ar_zero = np.zeros (4)
ar_zero1 = np.zeros([2,3])

print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
import numpy as np          
ar_one = np.ones(4)
ar_one1 = np.ones([3,4])
print(ar_one)
print()
print(ar_one)

[1. 1. 1. 1.]

[1. 1. 1. 1.]


In [10]:
ar_em = np.array(4)
print(ar_em)

4


In [12]:
ar_rn= np.arange(4)
print(ar_rn)

[0 1 2 3]


In [13]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
import numpy as np          
ar_lin = np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


In [1]:
import numpy as np          
var = np.random.rand(4)
print(var)

[0.69310647 0.50915187 0.46776683 0.72698082]


In [8]:
import numpy as np          
var1 = np.random.rand(5)
print(var1)

[0.37229099 0.25640673 0.44267569 0.42792577 0.11648773]


In [3]:
import numpy as np         
var2 = np.random.rand(2,5)
print(var2)

[[0.38157921 0.05125207 0.25518608 0.22704873 0.52324075]
 [0.70644542 0.94792043 0.97598328 0.46261654 0.88054803]]


In [4]:
import numpy as np          
var3 = np.random.rand(2,3)
print(var3)

[[0.79442139 0.798111   0.73341562]
 [0.4306052  0.18963353 0.65281069]]


In [9]:
import numpy as np          
var_1 = np.random.randn(5)
print(var_1)

[ 0.38193103  0.71739501 -1.34806305 -0.80573605 -0.37569442]


In [11]:
import numpy as np         
var_2 = np.random.ranf(5)
print(var_2)

[0.72799424 0.9482269  0.9924102  0.53537862 0.90743641]


In [13]:
import numpy as np             

var = np.random.randint(5,20,5)
print(var)

[ 6 10  5 11  7]


In [14]:
import numpy as np         
var = np.array([1.0,1.2,1.3,1.4])
print("Data type:",var.dtype)

Data type: float64


In [15]:
import numpy as np            
varr = np.array([1.1, 1.2, 1.5,1.9])
print(var.dtype)

float64


In [19]:
import numpy as np         
var = np.array(["a","b","c","d"])
#print(var.dtype)
print("Data type :", var.dtype)

Data type : <U1


In [20]:
import numpy as np                
var4 = np.array([1,2,3,"a","b"])
print(var.dtype)

<U1


In [21]:
import numpy as np               
varrr = np.array([11,22,33,44])
print(varrr.dtype)

int32


In [24]:
import numpy as np
var = np.array([1,2,3,4,5],dtype=np.int8)
print(var)

[1 2 3 4 5]


In [26]:
import numpy as np          
var = np.array([1,2,3,4])
new = np.float32(var)
print("Data type : ",var.dtype)
print("Data type : ", new.dtype)
print(var)
print(new)

Data type :  int32
Data type :  float32
[1 2 3 4]
[1. 2. 3. 4.]


In [1]:
import numpy as np               
var = np.array([1,2,3,4])
varadd =var+3
print(varadd)

[4 5 6 7]


In [3]:
import numpy as np                
var =np.array([1,2,3,4])
var1 = np.array([5,6,7,8])
varadd = var + var1
print(varadd)

[ 6  8 10 12]


In [6]:
import numpy as np        
var = np.array([1,2,3,4])
var2 = np.array([11,22,33,44])
varadd = var + var2
print(varadd)

[12 24 36 48]


In [7]:
var = np.array([1,2,3,4])
varadd = var/3 
print(varadd)

[0.33333333 0.66666667 1.         1.33333333]


In [8]:
import numpy as np             
var = np.array([1,2,3,4])
var3 = np.array([1,2,3,4])
varsub = var - var3
print(varsub)

[0 0 0 0]


In [9]:
import numpy as np             
var = np.array([1,2,3,4])
varmod = var % 3
print(varmod)

[1 2 0 1]


In [10]:
import numpy as np           
var1 = np.array([[1,2,3,4],[5,6,7,8]])
var2 = np.array([[8,7,6,5],[4,3,2,1]])
print(var1)
print()
print(var2)
print()
varadd = var1 + var2
print(varadd)

[[1 2 3 4]
 [5 6 7 8]]

[[8 7 6 5]
 [4 3 2 1]]

[[9 9 9 9]
 [9 9 9 9]]


In [2]:
import numpy as np              
var = np.array([1,2,3,4,5])
print(var)
print("min : ",np.min(var))
print("max : ",np.max(var))

[1 2 3 4 5]
min :  1
max :  5


In [3]:
import numpy as np         
var = np.array([1,2,3,4,2,8,1,2])
print(var)
print('min : ', np.min(var), np.argmax(var))

[1 2 3 4 2 8 1 2]
min :  1 5


In [4]:
import numpy as np                 
var = np.array([1,2,3,4,5])
print(var)
print("max : ", np.max(var), np.argmax(var))

[1 2 3 4 5]
max :  5 4


In [9]:
import numpy as np              
var = np.array([[1,2,3,4],[5,6,7,8]])
print(var)
print(np.min(var, axis = 0))

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4]


In [13]:
import numpy as np                
var2 = np.array([1,2,3])
print(var2)
print(np.sin(var2))
print(np.cos(var2))
print(np.cumsum(var2))

[1 2 3]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[1 3 6]


In [1]:
import numpy as np                
var = np.array([[1,2,3],[4,5,6]])
print(var)
print()
print(var.shape)

[[1 2 3]
 [4 5 6]]

(2, 3)


In [5]:
import numpy as np                
var = np.array([[1,2,],[1,2,]])
print(var)
print()
print(var.shape)

[[1 2]
 [1 2]]

(2, 2)


In [7]:
var1 = np.array([1,2,3,4])
print(var1)
print(var1.ndim)
print(var1.shape)


[1 2 3 4]
1
(4,)


In [8]:
import numpy as np            
var2 = np.array([1,2,3,4,5,6,1,2,3])
print(var2)
print()
x = var2.reshape(3,3)
print(x)
print(x.ndim)

[1 2 3 4 5 6 1 2 3]

[[1 2 3]
 [4 5 6]
 [1 2 3]]
2


In [10]:
import numpy as np          
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print()
x = var3.reshape(2,3,2)
print(x)
print(x.ndim)
print()
one = x.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [6]:
import numpy as np              
var1 = np.array([1,2,3])
var2 = np.array([2,3,4])
print(var1 + var2)
#var = var1 + var2 
#print(var)

[3 5 7]


In [7]:
var1 = np.array([1,2,3,4])
print(var1.shape)
print(var1)

(4,)
[1 2 3 4]


In [8]:
var1 = np.array([1,2,3])
print(var1. shape)
print(var1)
print()
var2 = np.array([[1],[2],[3]])
print(var2)
print(var2.shape)
print()
print(var1 + var2)

(3,)
[1 2 3]

[[1]
 [2]
 [3]]
(3, 1)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [9]:
import numpy as np                
x = np.array([[1],[2]])
print(x.shape)

y = np.array([[1,2,3],[1,2,3]])
print(y.shape)
print()

print(x + y)

(2, 1)
(2, 3)

[[2 3 4]
 [3 4 5]]


In [10]:
import numpy as np            
var = np.array([9,8,7,6])
print(var[1])
print(var[-3])

8
8


In [ ]:
import numpy as np         
var2 = np.array([[9,8,7],[4,5,6]])
print(var2)
print(var2.ndim)
print(var2[1,2])

[[9 8 7]
 [4 5 6]]
2
6


In [20]:
import numpy as np            
var_1 = np.array([9,8,7,6,5,4,3])
print(var_1)
print()
#print("2 to 5 : ", var_1[1 : 5])
#print()
#print("2 to end : ", var_1[1:])
print()
print("stop :", var[::3])

[9 8 7 6 5 4 3]


stop : [9 6]


In [21]:
var = np.array([9,8,7,6,5,4])
print(var)
for i in var:
    print(i)

[9 8 7 6 5 4]
9
8
7
6
5
4


In [25]:
var2 = np.array([[1,2,3,4],[1,2,3,4]])
print(var2)
for j in var2:
    print(j)
print()
for k in var2:
    for l in j:
        print(l)

[[1 2 3 4]
 [1 2 3 4]]
[1 2 3 4]
[1 2 3 4]

1
2
3
4
1
2
3
4


In [28]:
import numpy as np           
var3 = np.array([[[1,2,3,4],[5,6,7,8],[3,4,5,6]]])
print(var3)
print()
for i in np.nditer(var3):
    print(i)


[[[1 2 3 4]
  [5 6 7 8]
  [3 4 5 6]]]

1
2
3
4
5
6
7
8
3
4
5
6


In [29]:
import numpy as np                 
var = np.array([1,2,3,4])
co = var.copy()
print("var : ", var)
print('copy : ', co)

var :  [1 2 3 4]
copy :  [1 2 3 4]


In [30]:
import numpy as np             
x = np.array([9,8,7,6,5])
vi = x.view()
print("x :", vi)

x : [9 8 7 6 5]


In [1]:
import numpy as np            
var = np.array([1,2,3,4])
var1 = np.array([5,6,7,8])

arr = np.concatenate((var,var1))
print(arr)

[1 2 3 4 5 6 7 8]


In [2]:
var = np.array([[1,2,3],[4,5,6]])
var1 = np.array([[7,8,9],[2,3,4]])
ar = np.concatenate((var,var1))
print(ar)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [2 3 4]]


In [4]:
import numpy as np            
var1 = np.array([1,2,3,4,5])
var2 = np.array([6,7,8,9,10])
var = np.stack((var1 , var2),axis = 1)
print(var)


[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [6]:
import numpy as np           
var = np.array([1,2,3,4,5,6,7,8])
print(var)
print()
ar = np.array_split(var,2)
print(ar)

[1 2 3 4 5 6 7 8]

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


In [8]:
import numpy as np            
var = np.array([1,2,3,4,5,6])
x = np.where(var==5)
print(x)

(array([4], dtype=int64),)


In [9]:
import numpy as np            
var = np.array([1,2,3,4,5,6,7,8])
x1 = np.searchsorted(var,5)
print(x1)

4


In [10]:
var = np.array([1,4,3,2,5,7,1,2,9])
print(np.sort(var))

[1 1 2 2 3 4 5 7 9]


In [11]:
import numpy as np         
var = np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var)

[3 4 5 1 2]


In [12]:
var = np.array([1,2,3,4,5,6,7])
x = np.unique (var)
print(x)


[1 2 3 4 5 6 7]


In [17]:
var = np.array([1,2,3,4,5,6])
y = np.resize(var2,(2,3))
print(y)

[[ 6  7  8]
 [ 9 10  6]]


In [18]:
import numpy as np                    
var = np.array([1,2,3,4])
print(var)
v = np.insert(var,(2,3),40)
print(v)

[1 2 3 4]
[ 1  2 40  3 40  4]


In [2]:
import numpy as np              
var1 = np.array([1,2,3,4])
print(var1)
var = np.delete(var1,3)
print(var)

[1 2 3 4]
[1 2 3]


In [3]:
import numpy as np             
var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print(type(var))

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


In [7]:
import numpy as np               
var1 = np.matrix([[1,2,3],[1,2,3]])
var2 = np.matrix([[1,2,3],[1,2,3]])
print(var1 - var2)

[[0 0 0]
 [0 0 0]]


In [10]:
import numpy as np           
var1 = np.array([[1,2],[1,2]])
var2 = np.array([[1,2],[1,2]])
print(var1 * var2)
print()
print(var1. dot(var2))

[[1 4]
 [1 4]]

[[3 6]
 [3 6]]


In [13]:
import numpy as np              
var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print(np.transpose(var))


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [14]:
var = np.array([[1,2,3],[4,5,6]])
print(np.swapaxes(var,0,1))

[[1 4]
 [2 5]
 [3 6]]
